### ISSUE TITLE
[Question] Automate fetching data?

### ISSUE THREAD

**Issue by Serpens66** [PillagingPagans/anno1800#1]
Hi,
nice mod :)

May I ask you how you created the spreadsheet? Manually or how? And what upkeep costs did you take when products have several different ways to be produced (easiest example coal, but meanwhile there are plenty of more difficult examples)

I'm asking because I made such a mod 2 years ago too and would like to update it. But meanwhile the game and the products are so complex, that I'm not sure how to fetch all the new products, their chain and which chain to use and so on.
Maybe you know a good way to do so?

My version, that is currently based on Game Version 9 is here:
https://github.com/Serpens66/Anno-1800-Mods/tree/master/Balanced%20Trading
I wrote a python script to automatically fetch all relevant values and do the calculation (and the mod does a bit more, see content.txt), but even this script needs instructions for what to look and which values to choose, if there are several chains for the same product and so on.

**Comment by PillagingPagans** [comment]
It was done by hand. I generally used the most efficient way, you can probably figure it out based on the spreadsheet (for coal, upkeep is 50, and production is set to 4. Electricity is not taken into account for the production value. So this means it was based off the mine, not the kiln).

It also hasn't been updated yet to latest update since I haven't really played much anno.
